sudo: required
services: 
  - docker

before_install:
  - docker build -t bobbymohanty/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run bobbymohanty/react-test npm test -- --coverage

after_success:
  - docker build -t bobbymohanty/mutli-client ./client
  - docker build -t bobbymohanty/mutli-nginx ./nginx
  - docker build -t bobbymohanty/mutli-server ./server
  - docker build -t bobbymohanty/mutli-worker ./worker
  # Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push Images to DockerHub
  - docker push bobbymohanty/mutli-client
  - docker push bobbymohanty/mutli-nginx
  - docker push bobbymohanty/mutli-server
  - docker push bobbymohanty/mutli-worker

# deploy:
#   provider: elasticbeanstalk
#   region: us-east-2
#   app: multi-docker
#   env: MultiDocker-env
#   bucket_name: elasticbeanstalk-us-east-2-941987523520
#   bucket_path: docker-multi
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: $AWS_SECRET_KEY
